export interface Config {
  LOG_LEVEL: string
  REDIS_HOST: string
  REDIS_PORT: number
  REDIS_DATABASE: number
  REDIS_USERNAME?: string
  REDIS_PASSWORD?: string
  POSTGRES_HOST: string
  POSTGRES_PORT: number
  POSTGRES_DATABASE: string
  POSTGRES_USERNAME?: string
  POSTGRES_PASSWORD?: string
  HEARTBEAT_CONCURRENCY: number
  HEARTBEAT_LIMITER_MAX: number
  HEARTBEAT_LIMITER_DURATION: number
  HEARTBEAT_QUEUE_USERS_LIMIT: number
  HEARTBEAT_QUEUE_PLANS_LIMIT: number
  HEARTBEAT_QUEUE_SUBSCRIPTIONS_LIMIT: number
  HEARTBEAT_QUEUE_CATEGORIES_LIMIT: number
}
