networks:
  avito-speculant-net:
    external: true

services:
  manager:
    image: ghcr.io/bitnoize/avito-speculant-manager:latest
    build:
      context: .
      dockerfile: ./apps/manager/Dockerfile
    environment:
      - UID=54720
      - GID=54720
      - NODE_ENV
      - LOG_LEVEL
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DATABASE
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
    networks:
      - avito-speculant-net
    restart: no

  bot:
    image: ghcr.io/bitnoize/avito-speculant-bot:latest
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    environment:
      - UID=54710
      - GID=54710
      - NODE_ENV
      - LOG_LEVEL
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DATABASE
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
      - BOT_TOKEN
    networks:
      - avito-speculant-net
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped

  worker-heartbeat:
    image: ghcr.io/bitnoize/avito-speculant-worker-heartbeat:latest
    build:
      context: .
      dockerfile: ./apps/worker-heartbeat/Dockerfile
    environment:
      - UID=54730
      - GID=54730
      - NODE_ENV
      - LOG_LEVEL
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DATABASE
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
      - HEARTBEAT_CONCURRENCY
      - HEARTBEAT_LIMITER_MAX
      - HEARTBEAT_LIMITER_DURATION
      - HEARTBEAT_FILLING_TREATMENT
      - HEARTBEAT_PRODUCE_USERS
      - HEARTBEAT_PRODUCE_PLANS
      - HEARTBEAT_PRODUCE_SUBSCRIPTIONS
      - HEARTBEAT_PRODUCE_BOTS
      - HEARTBEAT_PRODUCE_CATEGORIES
      - HEARTBEAT_PRODUCE_PROXIES
    networks:
      - avito-speculant-net
    restart: unless-stopped

  worker-treatment:
    image: ghcr.io/bitnoize/avito-speculant-worker-treatment:latest
    build:
      context: .
      dockerfile: ./apps/worker-treatment/Dockerfile
    environment:
      - UID=54730
      - GID=54730
      - NODE_ENV
      - LOG_LEVEL
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DATABASE
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
      - TREATMENT_CONCURRENCY
      - TREATMENT_LIMITER_MAX
      - TREATMENT_LIMITER_DURATION
    networks:
      - avito-speculant-net
    restart: unless-stopped

  worker-checkbot:
    image: ghcr.io/bitnoize/avito-speculant-worker-checkbot:latest
    build:
      context: .
      dockerfile: ./apps/worker-checkbot/Dockerfile
    environment:
      - UID=54750
      - GID=54750
      - NODE_ENV
      - LOG_LEVEL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
      - CHECKBOT_CONCURRENCY
      - CHECKBOT_LIMITER_MAX
      - CHECKBOT_LIMITER_DURATION
      - CURL_IMPERSONATE
    networks:
      - avito-speculant-net
    restart: unless-stopped

  worker-checkproxy:
    image: ghcr.io/bitnoize/avito-speculant-worker-checkproxy:latest
    build:
      context: .
      dockerfile: ./apps/worker-checkproxy/Dockerfile
    environment:
      - UID=54750
      - GID=54750
      - NODE_ENV
      - LOG_LEVEL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
      - CHECKPROXY_CONCURRENCY
      - CHECKPROXY_LIMITER_MAX
      - CHECKPROXY_LIMITER_DURATION
      - CURL_IMPERSONATE
    networks:
      - avito-speculant-net
    restart: unless-stopped

  worker-scraping:
    image: ghcr.io/bitnoize/avito-speculant-worker-scraping:latest
    build:
      context: .
      dockerfile: ./apps/worker-scraping/Dockerfile
    environment:
      - UID=54740
      - GID=54740
      - NODE_ENV
      - LOG_LEVEL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
      - SCRAPING_CONCURRENCY
      - SCRAPING_LIMITER_MAX
      - SCRAPING_LIMITER_DURATION
      - CURL_IMPERSONATE
    networks:
      - avito-speculant-net
    restart: unless-stopped

  worker-broadcast:
    image: ghcr.io/bitnoize/avito-speculant-worker-broadcast:latest
    build:
      context: .
      dockerfile: ./apps/worker-broadcast/Dockerfile
    environment:
      - UID=54780
      - GID=54780
      - NODE_ENV
      - LOG_LEVEL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
      - BROADCAST_CONCURRENCY
      - BROADCAST_LIMITER_MAX
      - BROADCAST_LIMITER_DURATION
    networks:
      - avito-speculant-net
    restart: unless-stopped

  worker-sendreport:
    image: ghcr.io/bitnoize/avito-speculant-worker-sendreport:latest
    build:
      context: .
      dockerfile: ./apps/worker-sendreport/Dockerfile
    environment:
      - UID=54760
      - GID=54760
      - NODE_ENV
      - LOG_LEVEL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DATABASE
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - QUEUE_REDIS_HOST
      - QUEUE_REDIS_PORT
      - QUEUE_REDIS_DATABASE
      - QUEUE_REDIS_USERNAME
      - QUEUE_REDIS_PASSWORD
      - SENDREPORT_CONCURRENCY
      - SENDREPORT_LIMITER_MAX
      - SENDREPORT_LIMITER_DURATION
    networks:
      - avito-speculant-net
    restart: unless-stopped

