export const DEFAULT_PROXYCHECK_CONCURRENCY = 2
export const DEFAULT_PROXYCHECK_LIMITER_MAX = 60
export const DEFAULT_PROXYCHECK_LIMITER_DURATION = 60_000
export const DEFAULT_PROXYCHECK_TEST_URL = 'https://www.google.com'
export const DEFAULT_PROXYCHECK_TEST_TIMEOUT = 10_000

export interface Config {
  LOG_LEVEL: string
  REDIS_HOST: string
  REDIS_PORT: number
  REDIS_DATABASE: number
  REDIS_USERNAME?: string
  REDIS_PASSWORD?: string
  POSTGRES_HOST: string
  POSTGRES_PORT: number
  POSTGRES_DATABASE: string
  POSTGRES_USERNAME?: string
  POSTGRES_PASSWORD?: string
  PROXYCHECK_CONCURRENCY: number
  PROXYCHECK_LIMITER_MAX: number
  PROXYCHECK_LIMITER_DURATION: number
  PROXYCHECK_TEST_URL: string
  PROXYCHECK_TEST_TIMEOUT: number
}
